### ISSUE TITLE
error'ing out when attempting to delete a non-existant file

### ISSUE THREAD

**Issue by major0** [stv-io/action-tfswitch#3]
The tfswitch action exits with an error when the file it tries to delete doesn't exist. This doesn't make any sense.

```
Version: 0.13.1308
Exporting PATH to GITHUB_PATH ..
Unlinking default version of terraform ..
unlink: cannot unlink '/usr/local/bin/terraform': No such file or directory
Error: Process completed with exit code 1.
```

**Comment by stv-io** [comment]
@major0 this might be the behaviour from tfswitch itself, I'm not sure, but it could be something that we can capture 

Can you give a bit more information and context where you are running this (runner version, underlying OS, etc?)

This might be due to the case that this was only tested on the ubuntu github actions runner, which have a default version of terraform pre-installed.

If you share details of the steps I can take to replicate this issue, I'll propose a fix, unless you want to try this yourself.

**Comment by stv-io** [comment]
Can you test whether the version in the PR solves this issue - https://github.com/stv-io/action-tfswitch/pull/4 ?

**Comment by kvendingoldo** [comment]
btw. you can also use [tenv](https://github.com/tofuutils/tenv) that support Terraform as well as OpenTofu (and Terragrunt :) ) in one tool. It allow you to simplify version management and can do much more, than tfswitch.

**Comment by stv-io** [comment]
Thanks for this pointer @kvendingoldo , do you know if there is a github action wrapping the installation and setup for this? I'll consider implementing it otherwise.

**Comment by kvendingoldo** [comment]
@stv-io for now no, but we're going to create it here: https://github.com/tofuutils/tenv-github-action
welcome to contribute :)

**Comment by stv-io** [comment]
Awesome, will follow and contribute for sure!
